{ pkgs
, forceDontCheck
, enableProfiling
, enablePhaseMetrics
, enableBenchmarks
, fasterBuild
, enableDebugging
}:

with pkgs.lib;

let
  # the GHC we are using
  # at some point use: pkgs.haskell.compiler.ghc843;
  ghc = overrideDerivation pkgs.haskell.compiler.ghc822 (drv: {
    patches = drv.patches ++ [ ./patches/ghc-8.0.2-darwin-rec-link.patch ];
  });

  # This will yield a set of haskell packages, based on the given compiler.
  cardanoPkgsBase = ((import ../pkgs { inherit pkgs; }).override {
    inherit ghc;
  });

  # Overlay logic for *haskell* packages.
  requiredOverlay    = import ./overlays/required.nix     { inherit pkgs enableProfiling; };
  benchmarkOverlay   = import ./overlays/benchmark.nix    { inherit pkgs; };
  debugOverlay       = import ./overlays/debug.nix        { inherit pkgs; };
  fasterBuildOverlay = import ./overlays/faster-build.nix { inherit pkgs; };
  dontCheckOverlay   = import ./overlays/dont-check.nix   { inherit pkgs; };
  metricOverlay      = import ./overlays/metric.nix       { inherit pkgs; };

  activeOverlays = [ requiredOverlay ]
  ##  ++ optional enablePhaseMetrics metricOverlay  # Removed temporarily
      ++ optional enableBenchmarks benchmarkOverlay
      ++ optional enableDebugging debugOverlay
      ++ optional forceDontCheck dontCheckOverlay
      ++ optional fasterBuild fasterBuildOverlay;

in
  # Apply all the overlays on top of the base package set generated by stack2nix
  builtins.foldl' (pkgs: overlay: pkgs.extend overlay) cardanoPkgsBase activeOverlays
