resolver: lts-9.1

packages:
- '.'

extra-deps:
  - universum-0.7.0
  - serokell-util-0.5.0
  - servant-quickcheck-0.0.3.1
  - acid-state-0.14.3
  - log-warper-1.3.3
  - time-units-1.0.0
  - fmt-0.5.0.0
  - servant-0.10
  - servant-server-0.10
  - servant-client-0.10

nix:
  shell-file: ../shell.nix
