resolver: lts-9.1

packages:
- '.'

# Unreleased support for servant-0.12
- location:
    git: https://github.com/haskell-servant/servant-quickcheck.git
    commit: 6e6595f68c947107beba185392b350abd2009ba0
  extra-dep: true

extra-deps:
  - universum-0.7.0
  - serokell-util-0.5.0
  - acid-state-0.14.3
  - log-warper-1.3.3
  - time-units-1.0.0
  - fmt-0.5.0.0
  - servant-0.12
  - servant-server-0.12
  - servant-client-0.12

nix:
  shell-file: ../shell.nix
