##############################################################################
##                                                                          ##
##   Testnet configs                                                        ##
##                                                                          ##
##############################################################################

mainnet_base: &mainnet_base
  core: &mainnet_base_core
    genesis: &mainnet_base_genesis
      spec: &mainnet_base_spec
        initializer:
          testnetInitializer:
            testBalance:
              poors:        1200
              richmen:      4
              richmenShare: 0.94
              totalBalance: 12887504355000000
              useHDAddresses: False
            fakeAvvmBalance: 
              count: 100
              oneBalance: 15000000
            distribution: 
              testnetRichmenStakeDistr: []
            seed: 0
        blockVersionData:
          scriptVersion:     0
          slotDuration:      20000
          maxBlockSize:      2000000
          maxHeaderSize:     2000000
          maxTxSize:         4096 # 4 Kb
          maxProposalSize:   700 # 700 bytes
          mpcThd:            0.02 # 2% of stake
          heavyDelThd:       0.0003 # 0.03% of stake
          updateVoteThd:     0.001 # 0.1% of total stake
          updateProposalThd: 0.1 # 10% of total stake
          updateImplicit:    10000 # slots
          softforkRule:
            initThd:        0.9 # 90% of total stake
            minThd:         0.6 # 60% of total stake
            thdDecrement:   0.05 # 5% of total stake
          txFeePolicy:
            txSizeLinear:
              a: 155381 # absolute minimal fees per transaction
              b: 43.946 # additional minimal fees per byte of transaction size
          unlockStakeEpoch: 
            getEpochIndex: 0 # last epoch (maxBound @Word64)
        protocolConstants:
          k: 2160
          protocolMagic: 60987900
          vssMinTTL: 2
          vssMaxTTL: 6
        ftsSeed: "c2tvdm9yb2RhIEdndXJkYSBib3JvZGEgcHJvdm9kYSA="
        heavyDelegation:
          genesisDelegation: {}
        avvmDistr:
          avvmData: []

    dbSerializeVersion: 0
    memPoolLimitRatio: 2 # mem pool will be limited by this value
                         # muliplied by block size limit
    # Chain quality thresholds and other constants to detect suspicious things
    nonCriticalCQBootstrap: 0.95
    criticalCQBootstrap: 0.8888
    nonCriticalCQ: 0.8
    criticalCQ: 0.654321
    criticalForkThreshold: 3 # number of blocks such that if so many blocks are
                             # rolled back, it requires immediate response
    fixedTimeCQ: 3600 # Chain quality will be also calculated for this amount
                    # of seconds.
    # Mode-sensitive logging options
    webLoggingEnabled: true

  infra:

    # NTP
    ntpResponseTimeout: 10000000           # 10 sec
    ntpPollDelay: 60000000                 # 1 min
    ntpMaxError: 120000000 # 2 mins

    neighboursSendThreshold: 2
    kademliaDumpInterval: 4
    enhancedMessageTimeout: 360 # 6 mins
    enhancedMessageBroadcast: 2
    networkWaitLogInterval: 32 # 1s

    maxReqSize: 102 # 102 bytes
    maxInvSize: 102 # 102 bytes
    maxMempoolMsgSize: 100 # 100 bytes

  update:
    applicationName: cardano-sl
    applicationVersion: 0
    lastKnownBlockVersion:
      bvMajor: 0
      bvMinor: 0
      bvAlt: 0
    systemTag: system

  # GodTossing
  gt:
    mpcSendInterval: 100 # must be less than (2 * k * slotDuration - networkDiameter)
    mdNoCommitmentsEpochThreshold: 3

  node:
    # FIXME avieth
    # check which of these are not used and remove them.
    networkDiameter: 18
    defaultPeers: []
    mdNoBlocksSlotThreshold: 18 # should be less than 2 * k
    lightDlgConfirmationTimeout: 500
    dlgCacheParam: 500
    recoveryHeadersMessage: 2200 # should be greater than k
    messageCacheTimeout: 30
    networkConnectionTimeout: 2000
    blockRetrievalQueueSize: 100
    propagationQueueSize: 100
    pendingTxResubmissionPeriod: 7 # seconds

meta:
  <<: *mainnet_base
  core:
    <<: *mainnet_base_core
    genesis:
      <<: *mainnet_base_genesis
      spec: 
        <<: *mainnet_base_spec
        avvmDistr:
          avvmData: &mainnet_avvmDistr
            - {"coin":3846153,"address":"m2MIpUqWMTQJwK9F4LnaNstGh4BjMy2L2GDHpsuCAPA="}
            - {"coin":576688,"address":"bfBIoudbraZ4HVzIIIqQaa0RAp6Bx5cpHp1eRJyk_Uc="}
            - {"coin":417632,"address":"r6mogDtJ950dv8MqzxMoVQqBoDR11GBKXDtdPA3i4Rk="}
            - {"coin":1153846,"address":"OjTxauCTmi8n23ZvlFu_xBO4C762v2-4HzdCh1lniT8="}
            - {"coin":839786,"address":"D9_BqUsLHoxCVv8-x_t0JCSp5bld1QJT8ULtDywukCY="}
            - {"coin":5206939,"address":"SxstyLEeun2n1YZtUjpqzjV0RZ1BL2MDTo9upiTh_38="}
            - {"coin":384446,"address":"ucOY5l7LuolidjvnCyj3zTp738sNHeYLNnCUSPlHQEw="}
            - {"coin":908730,"address":"I-6IudnQPJOeMjlD3O9-Q3EU5D_UWkCo8o5pcNGlBHA="}
            - {"coin":384313,"address":"v86r37TE8jrPi3Mp1CwpfAZVqPSDWdXPqBMpGvANuyU="}
            - {"coin":800786,"address":"WUVmGDUE7466I6kjstj1NK3CozLxWs9ozxDs0C78Vj4="}
            - {"coin":386248,"address":"p3HIizxd6TgcVuthXERxpjPL_a_Fh058pulwgFYZJYg="}
            - {"coin":391305,"address":"f84qTWaSjc6K2qi1NBDumYH5I34ZGF7hT2abxI9Lthk="}
            - {"coin":8333333,"address":"0cAZzmtB2CUjlsMULb30YcBrocvK7VhQjUk--MyY2_Q="}
            - {"coin":385509,"address":"eYnJhdgbZSFudt8hacC43PB791qGvIn36O5xHDHIFHo="}
            - {"coin":458402,"address":"6oPTzkaLessyL2UojRWGuBolkCRTXh0HaxFjoEtA_M0="}
            - {"coin":458901,"address":"k7EFxAZRty8nVD7rscpP2z5hQUalA2XHp9LeogYnQQE="}
            - {"coin":1233257,"address":"gPdIsZ0D8DxdS2qM7tCycF94uGYDaSFL5sKaSMGY9wY="}
            - {"coin":411085,"address":"5y9_F3I9d4QVIEbl714W5JvDlNsZkSP0v5zdNqE0N4k="}
            - {"coin":388356,"address":"V2HzKow0u9iygL8Xs7e_5vR1YuCm98t7c46U5uHX5kg="}
            - {"coin":3766933,"address":"x72g7AK-9x8pdFJmDuD89oBmIpXObTOlZQ34sb1R_2I="}
            - {"coin":2079182,"address":"DUaqzBKEGqN4gMNaoNmN0p2zn_TfahX2rfI5_uGepk0="}
            - {"coin":473771,"address":"dMAl1ZvQ9x7lpU7E3R_PFfb9FHKg3yNq80iz82M2IBk="}
            - {"coin":3700966,"address":"pgEEswff7AzBO6uQJFcWUm7FPxPDVRCdWHfoPrKYiPc="}
            - {"coin":769230,"address":"v7C9SKh7MivNfbWn4zmcv-mcKQTDqg_B1VWlp0R8MN0="}
            - {"coin":417321,"address":"iK8aHzl9mgtWEXEi393FOyqd8VsB_3Srj4pYhdzCfhQ="}
            - {"coin":378966,"address":"ht33wNW5h8jUzSSzgz5QPv1dKYG4m1WZ1RGyk9dmNK4="}
            - {"coin":4654118,"address":"kDRCHCKvX79BAG82K271SMLTgI2vlEJgt_qvwiEWDH4="}
            - {"coin":2606663,"address":"TqYkqfYDjymw6xYZjGfUZdxMT4E_pKk4-TZNjPFlOyg="}
            - {"coin":385507,"address":"YxElsSEyXk4JIbekebeJHuI1qEQfyvaPuovsLbuQiE8="}
            - {"coin":4125716,"address":"LSxL3LjwnuSp6o-VmjccwjMeIa1UVgrrcgyPx5TdXug="}
            - {"coin":417948,"address":"NiVaK9EC3hEVdgtUU5Pwepps4xQfeekzc2dT3bQLHr0="}
            - {"coin":2365055,"address":"H0aufDSDD5_1KbgB8jwEkt7TvAdty3LuG20V_IFPXYA="}
            - {"coin":415629,"address":"CML31azQDGhg1-zG-pUCQzuzw7urhXTqMn8oyT4gV44="}
            - {"coin":377468,"address":"LWYl_wFwgT7_MdIOF-yet40Fa2oDGWyDJgasmPnaIT8="}
            - {"coin":502779,"address":"7RYRDszwooGHt3mJOA7NYlC8cVfxLT6MFyAB1VYHY0U="}
            - {"coin":455860,"address":"CoUnkM8F3qTh6yMdBmgGlCVEzEWGwNu4FxbrnPzRSO8="}
            - {"coin":1382699,"address":"e4Ed2RL9PnP8pav6lMAEMqDjqlh5H3tmNV4BkifQ86E="}
            - {"coin":385614,"address":"pZte3cEQ98qdueGRGDLEjAhJ22kD_1QmKi02EFdsM2c="}
            - {"coin":4090909,"address":"2KUqLLAcBam6HT-cBsIbccrJ9RsPrjxNdEtNnK_doWg="}
            - {"coin":769764,"address":"el1OTg2Dacf5wd7g2F1NN0oqbQj7aOglGGQsBo21fDE="}
            - {"coin":385510,"address":"8j6i5UZHcb3EcnlnTHtaoMmDdMt3FyEyLjS1KqNy66M="}
            - {"coin":1233257,"address":"8dc48d73Q5BBQ0ac8K9fTSEGebb9O7LZNcnhX9ThqYw="}
            - {"coin":602785,"address":"7xgRrZD4d1zDQgTbDNujzSMxOuKa-EmV4brSPVzL4-A="}
            - {"coin":1252906,"address":"7ZQr0WW6Fl1km1hj5qA6WUuAKFMo1fwDfgDiKaPj1ME="}
            - {"coin":1153856,"address":"Vb9EK9J-8kOnjiXrdu56niFgdysOV87UhtWjEeimp0s="}
            - {"coin":791457,"address":"yHPwxPwwvtqxS8t-U_i2rF3mbNL3yKc1UAhKTuADmbU="}
            - {"coin":460976,"address":"oGvvo0793rmOqMcJ8yolbnCT6lZpvhNuwPwvV5UwFIU="}
            - {"coin":355007,"address":"4_t2TrsmzNj_1u0M-Uh8w4ZEIx-0fQqwfhF9CF45sAc="}
            - {"coin":689346,"address":"bB-pyVyPHBuBQQM0bQMjBw_S7kihB87NJe2Z2k-kuPU="}
            - {"coin":384615,"address":"KTEkUlTC_u7JCfIYB4Hjt-tQkb0YpowA7tfEZtlCs48="}
            - {"coin":381024,"address":"9gTyoEMpaO5-uXTcC26hEea8INaeawOvHr7sVDUq21c="}
            - {"coin":6550435,"address":"r-xhv7T7Z2FLlk3tNFxJlPROXd4GYIAhkw6kCdmmuCM="}
            - {"coin":416408,"address":"s1U-738Ktinbb6aAqiaLGuDASomJm4PsjCLNDzGMe4Y="}
            - {"coin":461997,"address":"lvMXmGsZwLSxJtDv9SRYKYq3jiECUtN85dhLJiy8fpo="}
            - {"coin":1927483,"address":"NrfhKRH-CJn99vVsjMOSwF0pPRm9lvyE0WWerDdsKU0="}
            - {"coin":2088168,"address":"iZNtWQPUuo2Dx4HwezOscLntiZmmKIUjMr8HHjynOSg="}
            - {"coin":501244,"address":"yTKNsrfHVZf3YbEmyBR6Pg6yIs85ksa57YUuui8rcuQ="}
            - {"coin":4678221,"address":"TPSrjxo6_DDfpbSPivjzIO7JmUw0_QnRSJBXnGT_x5o="}
            - {"coin":411085,"address":"yUAtXs7LHVfUEDexSnDxmVt-th19El9BQJXrClLqlkE="}
            - {"coin":4082823,"address":"4FQyuUBGL-SN-iKog88vdLXwbAS-o8CS6VFWCxyP9ZA="}
            - {"coin":426259,"address":"ZdxSYu8o2sg3SGN5CWVoPu3GbXHVE0pWXdWuqqNKejo="}
            - {"coin":384615,"address":"YobJ3KDcRueyphVSgNG56PJ_tChMxwZLOdsSOehGmO8="}
            - {"coin":1249361,"address":"djzWPVvdMzesxKnkEgbMmcz_AGi3GqLA5gWM3-x4pkU="}
            - {"coin":4166673,"address":"MbNoWAfJz1kxPfxQKenxUc2UrvEU64SiS_iQPwkpblc="}
            - {"coin":459512,"address":"Hy6D76MK15JGzIKpRCgC-JSxO-V3j3aY5kX5PGhnVyE="}
            - {"coin":519045,"address":"ZisFK6CMMpcdvDGfJf7L_zEbEwv2AQGuDAvihXRKMN8="}
            - {"coin":1773135,"address":"zE56EfVAvv0XekVyBDGh2Iz1QT6X38YxlcBYO20hqa0="}
            - {"coin":1542961,"address":"7Hcjr9PP6E8bTnXm9Cxqm0xF12cIVrP-5rWRCg2TAM0="}
            - {"coin":473228,"address":"FWmJ0_1W-bj4VkEWXmt5rZ9Rcx0oKH5-5ZOZrxFtPdQ="}
            - {"coin":1997136,"address":"xxppattN3Jva0ovJ3GwEjHqV8U5QU8BwJvbm2cRM_-o="}
            - {"coin":383327,"address":"LnehWSU7azjKkCnHPu0oKuq_Kr1WaFDqAqe7j41sLhQ="}
            - {"coin":2344096,"address":"pzpFgbhUwl-nIZyPb8NDAfeFVMSvYN3v92o1XGoh7u0="}
            - {"coin":1126724,"address":"HwvLBXZFFCUPqoslZAOxDe432bRDiUxu4AAaVoW_KBk="}
            - {"coin":550159,"address":"ha0Wt3rzoGIh1gZ4_vAyHVIPii7HGY3VCA4X8KNR8Mw="}
            - {"coin":391838,"address":"cKz_4p3JT77fHWfP7cwI0hzBHlh8KenTagQAy-FMc5U="}
            - {"coin":4188555,"address":"2g1y4AdNX20RNxY3NlrmM9q46fw-xALfIfu1ZxFGJnQ="}
            - {"coin":384615,"address":"Rb7DXtAbKHWgmim0tD-YFoF6FKMQo1N04KWd8_nFeZ8="}
            - {"coin":384567,"address":"4jaczUQ3yiYZJCoOlPwQGIEP1tRegtsde0sy-0ucRn8="}
            - {"coin":384615,"address":"uzqhfjutcyRNbXxAeHLFCvivChaZnU3PdV1osIfMGZs="}
            - {"coin":2185607,"address":"4tw6-vDx_CN-zyjTX0UIrOw04V2-6OfPTniG2Kb-e5c="}
            - {"coin":584874,"address":"YIcLPUPh_g5X4CDaMU_2XyIlwIDbuq4rKDJjLq9375Y="}
            - {"coin":769230,"address":"oeyEIHKNKHSIEtWFyfJUzh3Vu6ObhHiNC8lbUjhryO8="}
            - {"coin":466657,"address":"W_rxpiElzvcUQvjaGeUlTcUveKHWz8_h6h4BGWKoAHI="}
            - {"coin":769230,"address":"l9AfCitT8Om-L-K_Fapz3YDFVwb4rZrU-MGIFXObJ7k="}
            - {"coin":5517798,"address":"LcoE-FnAFHTuUFrTezU8g_twqRQ4LkPpTwhPYdOnyTA="}
            - {"coin":384615,"address":"sNzQ_LxmRMWEEXJCknRKdUOYgcljThjmI6oXWiHJSEw="}
            - {"coin":473331,"address":"YTmm-vscsR_BoUICWMPTHgVjMxgO0vr2GfLHaM4qENk="}
            - {"coin":542442,"address":"FbjXXzvlbjAPQbmMe2Vpe-JMGA5vFP1H0ZbDOeVtFEk="}
            - {"coin":769230,"address":"cuz03qVirEEFKMeGEgYElpJWJDY_m3S7acGML9szudg="}

mainnet: &mainnet
  <<: *mainnet_base
  core:
    <<: *mainnet_base_core
    genesis:
      src: sample-mainnet-genesis.json

mainnet_generated: &mainnet_generated
  <<: *mainnet_base
  core:
    <<: *mainnet_base_core
    genesis:
      <<: *mainnet_base_genesis
      spec: 
        <<: *mainnet_base_spec
        avvmDistr:
          avvmData: *mainnet_avvmDistr
        initializer:
          mainnetInitializer:
            startTime:     
              timestamp:   1505621332 
            bootStakeholders: 
              genesisWStakeholders:
                  0d916567f96b6a65d204966e6aab5fbd242e56c321833f8ba5d607da: 1
                  4bd1884f5ce2231be8623ecf5778a9112e26514205b39ff53529e735: 1
                  5f53e01e1366aeda8811c2a630f0e037077a7b651093d2bdc4ef7200: 1
                  ada3ab5c69b945c33c15ca110b444aa58906bf01fcfe55d8818d9c49: 1
            vssCerts: 
              0d916567f96b6a65d204966e6aab5fbd242e56c321833f8ba5d607da:
                expiryEpoch: {getEpochIndex: 1}
                signature: "5cabf2789a8f6830707a5f661e4b52ef8de46b6dff8ba8a164d85a870c5c945963f0a806a591133dbff9e61e0532db03a0434547447004fc618c6e3ad0750c0f"
                signingKey: "oUDzVUqwmXH4E3RlDrS4zhZ6kwv9rnNiwe8dI6lIg794+bWQBlULwvnwiIGgK4z0HT8+o+nru8F5xDy4ZL2/lA=="
                vssKey: "WCEChSQx6z4OxYrHNYbu5GGztX4FBBxGMfzmO6C+xNTrDVw="
              4bd1884f5ce2231be8623ecf5778a9112e26514205b39ff53529e735:
                expiryEpoch: {getEpochIndex: 1}
                signature: "fb4aed3ecb4fb180f222ab63572684af5e749be1bc8d0903e72753080baa6bc4fd97a9d18318c7f25c9153622352510500e4850dd3d145c35c4af897d86ba203"
                signingKey: "ohsV3RtEFD1jeOzKwNulmMRhBG2RLdFxPbcSGbkmJ+xd/2cOALSDahPlydFRjd15sH0PkPE/zTvP4iN8wJr/hA=="
                vssKey: "WCECtpe8B/5XPefEhgg7X5veUIYH/RRcvXbz6w7MIJBwWYU="
              5f53e01e1366aeda8811c2a630f0e037077a7b651093d2bdc4ef7200:
                expiryEpoch: {getEpochIndex: 1}
                signature: "41a59561f6bf0b402853b153b4f2762e5cbd19ba0159d0b08a6c4a8dcb01964fcdb8672320bf73db9aed1ea65b60d2bdc308d89cead3f0b35cead88463f18006"
                signingKey: "E8++WAjZOKIyoh4YEHNaV7cm3Ecut7G9N0AT36u+AoSMEvf/byG8fc/Ab4xSnjvdn5Ww8A+yPOyoZ3Jfb2yf+g=="
                vssKey: "WCEDIRsfuDpNYMle1T396UpVmS/hEJgxVSQbCOynlK0zFEo="
              ada3ab5c69b945c33c15ca110b444aa58906bf01fcfe55d8818d9c49:
                expiryEpoch: {getEpochIndex: 1}
                signature: "4c9573885ecdbc3deff84b50e0160fbda1f1867d299ceeb51dc6e74effb3970d405296b31dd4f4b3e114ba783bf231900de5dbf874aeba57b0e83742adebf60e"
                signingKey: "oyGcGsd/FX3Zl98PPt/jE/mo+6Mz/HxaVcHxhrtxh6MrBkBi2U4h0pwaPDhWUo+IgcGzl4xLOqkoB4suojuNUA=="
                vssKey: "WCECjvlu5JR4+jdL44S/UIxpY1rcWaF75VeoGhhs8QQueiQ="
            nonAvvmBalances: {}
