resolver: lts-7.16
compiler: ghc-8.0.2

flags: {}

extra-package-dbs: []

packages:
- '.'
- core

- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: bf65ac0cd50d2ccd7ef6507f0d71786c4bd10ae1
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: 4e3f6a268c3b13af78516f78ac71cd6215f5b0bf
  extra-dep: true
- location:
    git: https://github.com/serokell/rocksdb-haskell.git
    commit: 4dfd8d61263d78a91168e86e8005eb9b7069389e
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: 57adb970e198a9b377769ab46e776ec29f19cff6
  extra-dep: true
- location: 
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: ede7a1a9eafd88e3449b38c7425f5529d6584014
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: b913bfc698fd2927ee5031826688eb7245906e6d
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/avieth/network-transport-tcp
    commit: d2705abd5b54707ca97b5bf9c9c24005e800ee49
  extra-dep: true
- location:
    git: https://github.com/avieth/network-transport
    commit: e7a5f44d0d98370d16df103c9dc61ef7bf15aee8
  extra-dep: true
# todo replace it with hackage version
#- location:
#    git: https://github.com/serokell/serokell-util/
#    commit: 3675d2e8484c4e1bab98c92a4c9b01ca721ff808

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.2.1
- pqueue-1.3.2
- data-msgpack-0.0.8
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2
- cryptonite-openssl-0.3
- UtilityTM-0.0.4
- serokell-util-0.1.3.4
- pvss-0.1
- base58-bytestring-0.1.0
- log-warper-0.4.3
- turtle-1.3.1                    # earlier versions don't have 'stat'
- optparse-applicative-0.13.0.0   # needed for turtle
- criterion-1.1.4.0               # older criterion doesn't like optparse-0.13
- code-page-0.1.1                 # needed for criterion


# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything
