resolver: lts-8.13

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

packages:
- node
- core
- update
- infra
- db
- lrc
- lwallet
- ssc
- godtossing
- tools
- txp
- wallet
- explorer

- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: eedf6b1f6f6b931fa578cf886e36b8a3a9fcda0d
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: c2af07ab7d627556ed3f6185b062e4cd1fb5ad26 #master
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: 39fd29a944efdfd19270a5866ec4ee81ac80fe01 # master
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: 24dd213cef81d383083feb7f5d9ce4b8a6be8168
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 1cde8e3a8d9093bbf571085920045c05edb3eaa4
  extra-dep: true
# We're using forked version of 'swagger2' package because of bug in haddock package.
# Now we don't build Haddock-docs for this 'swagger2' package, and when that bug will
# be fixed, we'll back to Hackage-version.
- location:
    git: https://github.com/serokell/swagger2
    commit: 6cc2063e1c8da9e701f3ac95549b8a33be9605de
  extra-dep: true
#- location:
#    git: https://github.com/haskell-crypto/cryptonite.git
#    commit: 2932df9e243aa7ae7eb2b25d7c60fa77a30c6fb5
#  extra-dep: true
# We need to use the version on GH and not on Hackage as the
# latter seems to be broken due to some space-parsing issues.
- location:
    git: https://github.com/kazu-yamamoto/dns.git
    commit: c9b06eb77225c8bb2092f1169c093d7a04129e53 # 2.0.11
  extra-dep: true

# Required for explorer
- location:
    git: https://github.com/serokell/engine.io.git
    commit: a594e402fd450f11ad60d09ddbd93db500000632
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.4.3
- serokell-util-0.4.0
- pvss-0.1
- active-0.2.0.13
- base58-bytestring-0.1.0
- log-warper-1.1.2
- concurrent-extra-0.7.0.10       # not yet in lts-8
# - purescript-bridge-0.8.0.1
- cryptonite-0.23
- cryptonite-openssl-0.6
- directory-1.3.1.0               # https://github.com/malcolmwallace/cpphs/issues/8
- servant-0.10                    # servant-multipart supports version servant-10 only
- servant-server-0.10             # so it triggers another dependencies to be v10
- servant-swagger-1.1.2.1
- servant-multipart-0.10
- ether-0.5.1.0
- transformers-lift-0.2.0.1
- lens-4.15.3                     # not yet in lts-8
- pipes-interleave-1.1.1
- th-abstraction-0.2.2.0          # needed for lens
- rocksdb-haskell-1.0.0
- generic-arbitrary-0.1.0
- happy-1.19.5                    # https://github.com/commercialhaskell/stack/issues/3151
- entropy-0.3.7                   # https://github.com/commercialhaskell/stack/issues/3151
- cborg-0.1.1.0
- systemd-1.1.2

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `scripts/build/cardano-sl.sh' script
ghc-options:
  cardano-sl-core:       -Werror
  cardano-sl-db:         -Werror
  cardano-sl-ssc:        -Werror
  cardano-sl-infra:      -Werror
  cardano-sl-lrc:        -Werror
  cardano-sl-update:     -Werror
  cardano-sl-godtossing: -Werror
  cardano-sl-txp:        -Werror
  cardano-sl:            -Werror
  cardano-sl-tools:      -Werror
  cardano-sl-lwallet:    -Werror
  cardano-sl-wallet:     -Werror
  cardano-sl-explorer:   -Werror
