resolver: lts-12.26
compiler: ghc-8.4.4
#resolver: lts-14.21
#compiler: ghc-8.6.5

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

# The dependency graph which was previously here has been dropped in favor of
# PNG output from the script `scripts/package-dep-graph.sh`, which uses
# `stack dot` to construct a graph which represents the current state exactly.

packages:
- util
- util/test
- networking
- binary
- binary/test
- crypto
- crypto/test
- core
- core/test
- db
- db/test
- infra
- infra/test
- chain
- chain/test
- lib
- generator
- client
- auxx
- script-runner
- explorer
- node
- tools
- tools/post-mortem
- utxo
- wallet
- node-ipc
- faucet
- acid-state-exts
- x509
- cluster
- mnemonic
- yaml-validation

# IOHK projects:

- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 4590efa638397e952a51a8994b5543e4ea3c1ecd
  extra-dep: true
# to be removed when haskell-ip is in the current stackage version
- location:
    git: https://github.com/andrewthad/haskell-ip
    commit: 9bb453139aa82cc973125091800422a523e1eb8f
  extra-dep: true

## Vendored/Forked dependencies
#
# For these projects, please include a note describing:
# 1. why we're using a fork
# 2. what branch the commit is on
# 3. a link to the PR that upstreams the patch
#

# this extra-dep is to avoid printing microseconds with unicode
# no PR upstream was made
# TODO(parsonsmatt): why was this change done?
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true

# These three are needed for cardano-sl-networking
#
# This defines a bundle type and attribute:
# https://github.com/haskell-distributed/network-transport/compare/master...serokell:018a50b9042c2115c3ec9c9fd5ca5f28737dd29c?expand=1
# Seems relatively straightforward to PR.
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true

# This doesn't have much difference at all with the upstream master:
# https://github.com/haskell-distributed/network-transport-tcp/compare/master...serokell:3d56652123bd296dc759cd31947eb2a17924e68a?expand=1
# As above, seems relatively straightforward to PR.
- location:
    git: https://github.com/avieth/network-transport-tcp
    commit: 613332da47e2c3e4a79017ca188c9e6568671222
  extra-dep: true

# Works with latest network, because it does not depend upon network!
# Blew away the Acid.Remote modules, since we don't use them anyway.
- location:
    git: https://github.com/avieth/acid-state
    commit: 7c00aeeeb731f5c98fe1104693c0136b384cb824
  extra-dep: true

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- location:
    git: https://github.com/input-output-hk/engine.io
    commit: d3c55f51bb81cee7d0d551de930ce65fe7d76756
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

# Library has never been released on Hackage yet
- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: ddfe3593b80b5ceb88842bb7a6f2268df75d2c2f
  extra-dep: true


# The latest release of clock on hackage is *way* too old (0.7.2)
# and can not be cross compiled.  As
# https://github.com/corsis/clock/commit/f7fe4fb5691d56c342e6fbf5a99c121ab24a6b41
# hasn't made it into any release yet.
- location:
    git: https://github.com/corsis/clock.git
    commit: ef60bd51a3587a173adf565c33bf2886df6e3842
  extra-dep: true

# Library has never been released on Hackage yet
- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true

# Because log-warper mainline depends on a lifted-async which depends upon a
# buggy async
- location:
    git: https://github.com/input-output-hk/log-warper
    commit: 5271ab6c33541b8155ca203e714875974ec116be
  extra-dep: true

# Custom Universum prelude, that brings back some of the
# formatting logic, as well as `pretty`.
- location:
    git: https://github.com/input-output-hk/universum
    commit: 15f7db758ff5a24b874de2247f6f7a4576562da5
  extra-dep: true


# Need to adjust version bounds on serokell-util.
# serokell-util has an upper bound preventing 6.3 for some reason
- location:
    git: https://github.com/input-output-hk/serokell-util
    commit: 457f1d149c6e238841f283a1faf7bc8fb021b27d
  extra-dep: true

# Inspector, as used in cardano-crypto
- location:
    git: https://github.com/primetype/inspector.git
    commit: c975f4329365f0379c04358138e616fb96fb0b79
  extra-dep: true

nix:
  shell-file: nix/stack-shell.nix

extra-deps:
# Serokell-specific utilities not on stackage
- fmt-0.6

# Servant stuff not found on stackage
- servant-multipart-0.11.2

# Needed for coin selection in the wallet
- normaldistribution-1.1.0.3

# This used to be Serokell.Aeson.Options
- aeson-options-0.1.0
- servant-swagger-ui-redoc-0.3.0.1.21.2

# Needed to LTS-12.16 compatibility
- ether-0.5.1.0
- servant-quickcheck-0.0.7.2
- o-clock-0.1.1
- beam-sqlite-0.3.2.3
- katip-0.8.3.0
- Chart-1.9
- Chart-diagrams-1.9
- SVGFonts-1.6.0.3
- pvss-0.2.0
- systemd-2.0.0
- base58-bytestring-0.1.0
- pipes-interleave-1.1.3
- tabl-1.0.3
- loc-0.1.3.3
- hspec-2.5.5
- micro-recursion-schemes-5.0.2.2
- token-bucket-0.1.0.1
- lzma-clib-5.2.2
- megaparsec-7.0.4
- neat-interpolation-0.3.2.4
- config-ini-0.2.4.0
- stylish-haskell-0.9.2.2
- hedgehog-1.0

- network-3.1.0.1
- simple-sendfile-0.2.28
- io-streams-haproxy-1.0.1.0
- socks-0.6.0
- snap-server-1.1.1.1

- swagger2-2.4
  # Needed by swagger2 version (InsOrd module)
- insert-ordered-containers-0.2.2
  # Neede because of swagger2
- servant-swagger-1.1.7.1
  # Needed because of servant-swagger
- servant-0.15
- servant-client-0.15
- servant-client-core-0.15
- servant-server-0.15

- connection-0.3.0
- warp-3.2.27
- wai-extra-3.0.26

- wai-middleware-throttle-0.3.0.1 # cardano-wallet needs this


# katip-0.6.3.0 conflicts with Win32-2.6.1.0
allow-newer: true

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `scripts/build/cardano-sl.sh' script
ghc-options:
  cardano-sl:                   -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-auxx:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-binary:            -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-binary-test:       -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-chain:             -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-chain-test:        -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-client:            -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-core:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-core-test:         -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-crypto:            -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-crypto-test:       -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-db:                -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-db-test:           -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-explorer:          -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-generator:         -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-infra:             -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-networking:        -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-node:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-tools:             -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-tools-post-mortem: -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-util:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-util-test:         -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-node-ipc:          -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-x509:              -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-mnemonic:          -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-cluster:           -Wall -Werror -Wcompat -fwarn-redundant-constraints
  cardano-wallet:               -Wall -Werror -Wcompat -fwarn-redundant-constraints
