resolver: lts-11.2

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

# networking → [util, binary] → crypto → core → db → [lrc, infra] → [ssc, txp, update, delegation] → block → lib → ...
# Then we have two branches:
# ... → client → generator → [auxx, explorer, wallet] → wallet-new
# ... → [node, tools]
packages:
- networking
- binary
- util
- crypto
- core
- db
- lrc
- infra
- ssc
- txp
- update
- delegation
- block
- lib
- generator
- client
- auxx
- explorer
- node
- tools
- wallet
- wallet-new # The new (unreleased) version of the wallet

- location:
    git: https://github.com/well-typed/cborg
    # Has support for canonical cbor
    commit: 3d274c14ca3077c3a081ba7ad57c5182da65c8c1
  subdirs:
  - cborg
  extra-dep: true
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master
  extra-dep: true
- location:
    git: https://github.com/avieth/plutus-prototype
    commit: d094be301195fcd8ab864d793f114970426a4478
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 19fd5ddf24dab731375a156ce38dcfce4319d1e4 # master 0.4.9
  extra-dep: true
# These three are needed for cardano-sl-networking
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true
- location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 287cc575fafe86af9d24af9d012c47f9d3f04da0
  extra-dep: true

- location:
    git: https://github.com/haskell-crypto/cryptonite
    commit: 41d610fb18e2924d7aa704c37798e1c197557f3e
  extra-dep: true

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- location:
    git: https://github.com/input-output-hk/engine.io.git
    commit: d3c55f51bb81cee7d0d551de930ce65fe7d76756
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

# Version of "dns" with proper Windows & Unix multiple-nameservers support
- location:
    git: https://github.com/kazu-yamamoto/dns.git
    commit: b106470f0a93672af22cbc7ed6564b53c0f249ed
  extra-dep: true

- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: 2d261bb971bada1893753b503452d9e6e217bc4a
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true

# Because log-warper mainline depends on a lifted-async which depends upon a
# buggy async
- location:
    git: https://github.com/input-output-hk/log-warper.git
    commit: 5271ab6c33541b8155ca203e714875974ec116be
  extra-dep: true

# Because it includes a bunch of safecopy instances that we currently rely upon.
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 1049699df411c9584523ba7424cba1f3f82ac419
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:

# Very important! First release with a fix of 'race' and 'cancel'.
#   https://github.com/simonmar/async/issues/59
#   https://github.com/simonmar/async/issues/81
# It has yet to appear in an LTS.
- async-2.2.1
# There are 2 asyncs -_-
- lifted-async-0.10.0.1
# Stackage has hinotify-0.3.9 which requires async < 2.2
# This older version requires no async.
- hinotify-0.3.8.1

# Serokell stuff
- universum-1.1.0
- serokell-util-0.8.0
# Because serokell-util
- formatting-6.2.5

# Following 9 are not on stackage.
- pvss-0.2.0
- base58-bytestring-0.1.0
- pipes-interleave-1.1.2
- systemd-1.1.2
- tabl-1.0.3
- loc-0.1.3.2
- lens-sop-0.2.0.2
- json-sop-0.2.0.3
- lzma-clib-5.2.2
# TBD why not directory from LTS?
- directory-1.3.1.1
# https://github.com/commercialhaskell/stack/issues/3151
- happy-1.19.5
# https://github.com/commercialhaskell/stack/issues/3151
- entropy-0.3.7
# ekg-statsd version without the unnecessary diffing optimisation
- ekg-statsd-0.2.2.0
# https://github.com/fpco/lts-haskell/issues/70
# Also, graphviz latest needs ghl >=5.4 && <5.6, but stackage has 5.6
- fgl-5.5.3.1
# Good bug fixes in here.
- criterion-1.4.0.0
# Gauge _and_ criterion? Ok, whatever.
- gauge-0.2.1

# Servant stuff not found on stackage
- servant-quickcheck-0.0.6.0
- servant-multipart-0.11.1

# Graphics stuff not found on stackage.
- Chart-diagrams-1.8.2
- graphviz-2999.19.0.0
- diagrams-core-1.4.0.1
# diagrams-core implies lens < 4.16
- lens-4.15.4
# lens-4.15.4 implies free < 5
- free-4.12.4
- diagrams-lib-1.4.2
- diagrams-postscript-1.4
- diagrams-svg-1.4.1.1
- diagrams-solve-0.1.1
- SVGFonts-1.6.0.3
- dual-tree-0.2.1

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `scripts/build/cardano-sl.sh' script
ghc-options:
  cardano-sl-util:       -Werror
  cardano-sl-core:       -Werror
  cardano-sl-db:         -Werror
  cardano-sl-ssc:        -Werror
  cardano-sl-infra:      -Werror
  cardano-sl-lrc:        -Werror
  cardano-sl-update:     -Werror
  cardano-sl-txp:        -Werror
  cardano-sl-delegation: -Werror
  cardano-sl-block:      -Werror
  cardano-sl:            -Werror
  cardano-sl-client:     -Werror
  cardano-sl-generator:  -Werror
  cardano-sl-tools:      -Werror
  cardano-sl-auxx:       -Werror
  cardano-sl-wallet:     -Werror
  cardano-sl-explorer:   -Werror
  cardano-sl-node:       -Werror
  cardano-sl-wallet-new: -Werror
