resolver: lts-8.12

flags: {}

extra-package-dbs: []

packages:
- '.'
- core
- update
- infra
- db
- lrc

- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: b4b0a6774368b9bbea96d7a03a1a451b6fc3cfea
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: e2e2711e6978002279b4d7c49cab1aff47a2fd43
  extra-dep: true
- location:
    git: https://github.com/serokell/rocksdb-haskell.git
    commit: 4dfd8d61263d78a91168e86e8005eb9b7069389e
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: 57adb970e198a9b377769ab46e776ec29f19cff6
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 424e4ecacdf038a01542025dd1296bd272ce770d
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: 32bce17217e710e3e26210c660e05a1954b137cf
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/avieth/network-transport-tcp
    commit: ca42a954a15792f5ea8dc203e56fac8175b99c33
  extra-dep: true
- location:
    git: https://github.com/avieth/network-transport
    commit: f2321a103f53f51d36c99383132e3ffa3ef1c401
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 838b064d8a59286142aa2fe14434fe7601896ddb
  extra-dep: true
# We're using forked version of 'swagger2' package because of bug in haddock package.
# Now we don't build Haddock-docs for this 'swagger2' package, and when that bug will
# be fixed, we'll back to Hackage-version.
- location:
    git: https://github.com/serokell/swagger2
    commit: 6cc2063e1c8da9e701f3ac95549b8a33be9605de
  extra-dep: true
#- location:
#    git: https://github.com/haskell-crypto/cryptonite.git
#    commit: 2932df9e243aa7ae7eb2b25d7c60fa77a30c6fb5
#  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.4.1
- time-units-1.0.0
- serokell-util-0.1.5.0
- pvss-0.1
- base58-bytestring-0.1.0
- log-warper-1.1.2
- concurrent-extra-0.7.0.10       # not yet in lts-8
- purescript-bridge-0.8.0.1
- cryptonite-0.22
- directory-1.3.1.0               # https://github.com/malcolmwallace/cpphs/issues/8
- pipes-interleave-1.1.1
- servant-0.10                    # servant-multipart supports version servant-10 only
- servant-server-0.10             # so it triggers another dependencies to be v10
- servant-swagger-1.1.2.1
- servant-docs-0.10
- servant-multipart-0.10
- parsec3-numbers-0.1.0
- cryptonite-openssl-0.6

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `util-scripts/build.sh' script
ghc-options:
  cardano-sl-core:   -Werror
  cardano-sl-db:     -Werror
  cardano-sl-infra:  -Werror
  cardano-sl-lrc:    -Werror
  cardano-sl-update: -Werror
  cardano-sl:        -Werror
