resolver: lts-8.2

flags: {}

extra-package-dbs: []

packages:
- '.'
- core
- update
- infra
- db
- lrc

- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: bf65ac0cd50d2ccd7ef6507f0d71786c4bd10ae1
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: e2e2711e6978002279b4d7c49cab1aff47a2fd43
  extra-dep: true
- location:
    git: https://github.com/serokell/rocksdb-haskell.git
    commit: 4dfd8d61263d78a91168e86e8005eb9b7069389e
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: 57adb970e198a9b377769ab46e776ec29f19cff6
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 424e4ecacdf038a01542025dd1296bd272ce770d
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: 8631647810b950a21735d1466fa72348626213ed
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/avieth/network-transport-tcp
    commit: 1739cc6d5c73257201e5551088f4ba56d5ede15c
  extra-dep: true
- location:
    git: https://github.com/avieth/network-transport
    commit: f2321a103f53f51d36c99383132e3ffa3ef1c401
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 838b064d8a59286142aa2fe14434fe7601896ddb
  extra-dep: true
#- location:
#    git: https://github.com/haskell-crypto/cryptonite.git
#    commit: 2932df9e243aa7ae7eb2b25d7c60fa77a30c6fb5
#  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.3
- time-units-1.0.0
- serokell-util-0.1.4.0
- pvss-0.1
- base58-bytestring-0.1.0
- log-warper-1.0.3
- concurrent-extra-0.7.0.10       # not yet in lts-8
- derive-2.5.26                   # not yet in lts-8
- haskell-src-exts-1.17.1         # derive has not moved to 1.18 yet
- wreq-0.5.0.0                    # not yet in lts-8
- purescript-bridge-0.8.0.1
- cryptonite-0.22

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything
