flags: {}

extra-package-dbs: []

packages:
- '.'

- location:
    git: https://github.com/serokell/universum
    commit: d347ccf3605d0851dd0f7046fe63f364510ef1a0
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp.git
    commit: 8bf02bdbdb1da29af3b3d2c108a5a2d48f1ab75f
  extra-dep: true
- location:
    git: https://github.com/serokell/log-warper.git
    commit: d3b5f518e2827a961ba884a8009d4cfd4ccc737b
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 062053ed11b92c8e25d4d61ea943506fd0482fa6
  extra-dep: true
- location:
    git: https://github.com/serokell/double-conversion.git
    commit: cc7b810a08721a047c0241f0ef654dbebcef83f6
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- pqueue-1.3.2
- data-msgpack-0.0.8
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2
- cryptonite-openssl-0.3
- UtilityTM-0.0.4
- serokell-util-0.1.1.1
- pvss-0.1

resolver: lts-7.9
