resolver: lts-11.13

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

# util -> networking → binary →  crypto → core → db → [lrc, infra]
#              → [ssc, txp, update, delegation] → block → lib → ...
# Then we have two branches:
# ... → client → generator → [auxx, explorer, wallet] → wallet-new
# ... → [node, tools]
packages:
- util
- util/test
- networking
- binary
- binary/test
- crypto
- crypto/test
- core
- core/test
- db
- lrc
- lrc/test
- infra
- infra/test
- ssc
- txp
- txp/test
- update
- update/test
- delegation
- delegation/test
- block
- block/test
- block/bench
- lib
- generator
- client
- auxx
- explorer
- node
- tools
- wallet
- wallet-new # The new (unreleased) version of the wallet
- node-ipc
- acid-state-exts

- location:
    git: https://github.com/well-typed/cborg
    # Has support for canonical cbor
    commit: 3d274c14ca3077c3a081ba7ad57c5182da65c8c1
  subdirs:
  - cborg
  extra-dep: true
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master
  extra-dep: true
- location:
    git: https://github.com/avieth/plutus-prototype
    commit: d094be301195fcd8ab864d793f114970426a4478
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 81eea7361a75923f9402fcb7840fb36722dbf88e # master 0.4.10
  extra-dep: true
# These three are needed for cardano-sl-networking
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true
- location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 287cc575fafe86af9d24af9d012c47f9d3f04da0
  extra-dep: true
# Waiting on the flexible types PR to be merged:
# https://github.com/acid-state/acid-state/pull/94
- location:
    git: https://github.com/parsonsmatt/acid-state
    commit: 63ac55ae020655104936d8a90ccc6a939642cd0d
  extra-dep: true

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- location:
    git: https://github.com/input-output-hk/engine.io.git
    commit: d3c55f51bb81cee7d0d551de930ce65fe7d76756
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: 2d261bb971bada1893753b503452d9e6e217bc4a
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true

# Because log-warper mainline depends on a lifted-async which depends upon a
# buggy async
- location:
    git: https://github.com/input-output-hk/log-warper.git
    commit: fa925f9dadf239b38e2ffcc35f9d241a9fcb7d55
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/haskell-hedgehog.git
    commit: 2c9e51804e8217dff89f5c32cbe0d79ce20bc508
    subdirs:
      - hedgehog
  extra-dep: true

- location:
    git: https://github.com/avieth/servant-quickcheck.git
    commit: e4e879abca99d0d56015765859fb37af59a81dbb
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- cryptonite-openssl-0.7
  # - acid-state-0.14.3
# Very important! First release with a fix of 'race' and 'cancel'.
#   https://github.com/simonmar/async/issues/59
#   https://github.com/simonmar/async/issues/81
# It has yet to appear in an LTS.
- async-2.2.1
# There are 2 asyncs -_-
- lifted-async-0.10.0.1
# Stackage has hinotify-0.3.9 which requires async < 2.2
# This older version requires no async.
- hinotify-0.3.8.1

# Serokell stuff
- universum-1.1.0
- serokell-util-0.8.0
# Because serokell-util
- formatting-6.2.5

# Following 9 are not on stackage.
- pvss-0.2.0
- base58-bytestring-0.1.0
- pipes-interleave-1.1.2
- systemd-1.1.2
- tabl-1.0.3
- loc-0.1.3.2
- lens-sop-0.2.0.2
- json-sop-0.2.0.3
- lzma-clib-5.2.2
# TBD why not directory from LTS?
- directory-1.3.1.1
# https://github.com/commercialhaskell/stack/issues/3151
- happy-1.19.5
# https://github.com/commercialhaskell/stack/issues/3151
- entropy-0.3.7
# ekg-statsd version without the unnecessary diffing optimisation
- ekg-statsd-0.2.2.0
# https://github.com/fpco/lts-haskell/issues/70
# Also, graphviz latest needs ghl >=5.4 && <5.6, but stackage has 5.6
- fgl-5.5.3.1
# Good bug fixes in here.
- criterion-1.4.0.0
# Gauge _and_ criterion? Ok, whatever.
- gauge-0.2.1

# Servant stuff not found on stackage
- servant-multipart-0.11.1
# Because of servant-quickcheck
# It defines serverSatisfiesMgr, but requires a newer hspec.
- hspec-2.5.1
- hspec-core-2.5.1
- hspec-discover-2.5.1

# Graphics stuff not found on stackage.
- Chart-diagrams-1.8.2
- graphviz-2999.19.0.0
- diagrams-core-1.4.0.1
# diagrams-core implies lens < 4.16
- lens-4.15.4
# lens-4.15.4 implies free < 5
- free-4.12.4
- diagrams-lib-1.4.2
- diagrams-postscript-1.4
- diagrams-svg-1.4.1.1
- diagrams-solve-0.1.1
- SVGFonts-1.6.0.3
- dual-tree-0.2.1
- pretty-show-1.6.16
- cryptonite-0.25

# Support for wallet's Txmeta tracking
- sqlite-simple-errors-0.6.1.0

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `scripts/build/cardano-sl.sh' script
ghc-options:
  cardano-sl:             -Werror -fwarn-redundant-constraints
  cardano-sl-auxx:        -Werror -fwarn-redundant-constraints
  cardano-sl-binary:      -Werror -fwarn-redundant-constraints
  cardano-sl-binary-test: -Werror -fwarn-redundant-constraints
  cardano-sl-block:       -Werror -fwarn-redundant-constraints
  cardano-sl-block-bench: -Werror -fwarn-redundant-constraints
  cardano-sl-block-test:  -Werror -fwarn-redundant-constraints
  cardano-sl-client:      -Werror -fwarn-redundant-constraints
  cardano-sl-core:        -Werror -fwarn-redundant-constraints
  cardano-sl-core-test:   -Werror -fwarn-redundant-constraints
  cardano-sl-crypto:      -Werror -fwarn-redundant-constraints
  cardano-sl-crypto-test: -Werror -fwarn-redundant-constraints
  cardano-sl-db:          -Werror -fwarn-redundant-constraints
  cardano-sl-delegation:  -Werror -fwarn-redundant-constraints
  cardano-sl-explorer:    -Werror -fwarn-redundant-constraints
  cardano-sl-generator:   -Werror -fwarn-redundant-constraints
  cardano-sl-infra:       -Werror -fwarn-redundant-constraints
  cardano-sl-lrc:         -Werror -fwarn-redundant-constraints
  cardano-sl-lrc-test:    -Werror -fwarn-redundant-constraints
  cardano-sl-networking:  -Werror -fwarn-redundant-constraints
  cardano-sl-node:        -Werror -fwarn-redundant-constraints
  cardano-sl-ssc:         -Werror -fwarn-redundant-constraints
  cardano-sl-tools:       -Werror -fwarn-redundant-constraints
  cardano-sl-txp:         -Werror -fwarn-redundant-constraints
  cardano-sl-txp-test:    -Werror -fwarn-redundant-constraints
  cardano-sl-update:      -Werror -fwarn-redundant-constraints
  cardano-sl-util:        -Werror -fwarn-redundant-constraints
  cardano-sl-util-test:   -Werror -fwarn-redundant-constraints
  cardano-sl-wallet:      -Werror -fwarn-redundant-constraints
  cardano-sl-wallet-new:  -Werror -fwarn-redundant-constraints
  node-ipc:               -Werror -fwarn-redundant-constraints
