resolver: lts-11.13

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

# The dependency graph which was previously here has been dropped in favor of
# PNG output from the script `scripts/package-dep-graph.sh`, which uses
# `stack dot` to construct a graph which represents the current state exactly.

packages:
- util
- util/test
- networking
- binary
- binary/test
- crypto
- crypto/test
- core
- core/test
- db
- lrc
- lrc/test
- sinbin
- infra
- infra/test
- ssc
- ssc/test
- txp
- txp/test
- update
- update/test
- delegation
- delegation/test
- block
- block/test
- lib
- generator
- client
- auxx
- explorer
- node
- tools
- wallet
- wallet/test
- wallet-new # The new (unreleased) version of the wallet
- node-ipc
- acid-state-exts

# IOHK projects:

# TODO(parsonsmatt): There have been some breaking changes with Plutus for
# cardano-sl and it would be nice to have some help from that team to get this
# updated and back on IOHK.
- location:
    git: https://github.com/avieth/plutus-prototype
    commit: d094be301195fcd8ab864d793f114970426a4478
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 81eea7361a75923f9402fcb7840fb36722dbf88e # master 0.4.10
  extra-dep: true

- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 33c7ecc6e4bd71c3ea0195e9d796eeace7be22cf
  extra-dep: true

## Vendored/Forked dependencies
#
# For these projects, please include a note describing:
# 1. why we're using a fork
# 2. what branch the commit is on
# 3. a link to the PR that upstreams the patch
#
# Has support for canonical cbor. This commit is pulled into `master`. I've
# posted a GitHub issue requesting a Hackage release:
# https://github.com/well-typed/cborg/issues/171
- location:
    git: https://github.com/well-typed/cborg
    commit: 3d274c14ca3077c3a081ba7ad57c5182da65c8c1
  subdirs:
  - cborg
  extra-dep: true

# this extra-dep is to avoid printing microseconds with unicode
# no PR upstream was made
# TODO(parsonsmatt): why was this change done?
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true

# not reviewing this too deeply as we're dumping kademlia
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f # master
  extra-dep: true

# We're waiting on next release: https://github.com/thoughtpolice/hs-ed25519/issues/20
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true

# These three are needed for cardano-sl-networking
#
# This defines a bundle type and attribute:
# https://github.com/haskell-distributed/network-transport/compare/master...serokell:018a50b9042c2115c3ec9c9fd5ca5f28737dd29c?expand=1
# Seems relatively straightforward to PR.
- location:
    git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c
  extra-dep: true

# This doesn't have much difference at all with the upstream master:
# https://github.com/haskell-distributed/network-transport-tcp/compare/master...serokell:3d56652123bd296dc759cd31947eb2a17924e68a?expand=1
# As above, seems relatively straightforward to PR.
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: 3d56652123bd296dc759cd31947eb2a17924e68a # csl-0.6.0
  extra-dep: true

# This one has more changes:
# https://github.com/haskell-distributed/network-transport-inmemory/compare/master...avieth:5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a?expand=1
# Do we have an issue that documents why we made these changes, so we can make a PR upstream?
- location:
      git: https://github.com/avieth/network-transport-inmemory
      commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a
  extra-dep: true

# Waiting on the flexible types PR to be merged:
# https://github.com/acid-state/acid-state/pull/94
- location:
    git: https://github.com/parsonsmatt/acid-state
    commit: 63ac55ae020655104936d8a90ccc6a939642cd0d
  extra-dep: true

# Required for explorer.
# We forked it because it has some unacceptable version bounds. We didn't
# add any features nor fix any bugs.
- location:
    git: https://github.com/input-output-hk/engine.io.git
    commit: d3c55f51bb81cee7d0d551de930ce65fe7d76756
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai

# Library has never been released on Hackage yet
- location:
    git: https://github.com/well-typed/canonical-json.git
    commit: 2d261bb971bada1893753b503452d9e6e217bc4a
  extra-dep: true

# Library has never been released on Hackage yet
- location:
    git: https://github.com/input-output-hk/rocksdb-haskell-ng.git
    commit: 49f501a082d745f3b880677220a29cafaa181452
  extra-dep: true

# Because log-warper mainline depends on a lifted-async which depends upon a
# buggy async
- location:
    git: https://github.com/input-output-hk/log-warper.git
    commit: 4af8114fbcd5698a4e1fbc653031f0300e29faee
  extra-dep: true

# Exposes a custom discovery function so you can specify the prefix.
# https://github.com/hedgehogqa/haskell-hedgehog/compare/master...input-output-hk:master
- location:
    git: https://github.com/input-output-hk/haskell-hedgehog.git
    commit: 2c9e51804e8217dff89f5c32cbe0d79ce20bc508
    subdirs:
      - hedgehog
  extra-dep: true

# servant-quickcheck has a doc/doc.cabal file that is poorly specified and this
# breaks the mafia build tool.
- location:
    git: https://github.com/avieth/servant-quickcheck.git
    commit: e4e879abca99d0d56015765859fb37af59a81dbb
  extra-dep: true

# Add custom stylish-haskell while waiting for PR upstream: https://github.com/jaspervdj/stylish-haskell/pull/214
- location:
    git: https://github.com/input-output-hk/stylish-haskell.git
    commit: ecfd3b307d8d13a6d12aff03055f25a39a17e182
  extra-dep: true

# Custom Universum prelude, that brings back some of the
# formatting logic, as well as `pretty`.
- location:
    git: https://github.com/input-output-hk/universum.git
    commit: 7f1b2483f71cacdfd032fe447064d6e0a1df50fc
  extra-dep: true


# use github source, until we can use the 6.3.6 release from
# hackage, that is, once `cabal update` ran.
- location:
    git: https://github.com/chrisdone/formatting.git
    commit: 444bc8b1190f9c7f94af41b6f538071545392754
  extra-dep: true

# Need to adjust version bounds on serokell-util.
# serokell-util has an upper bound preventing 6.3 for some reason
- location:
    git: https://github.com/input-output-hk/serokell-util.git
    commit: 4ead9809e119483e7832da5f8224b0c4d4a2d5d6
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
# Needed to fix an issue with CTX_INIT failing to build on newer openssl
# versions.
- cryptonite-openssl-0.7
# Very important! First release with a fix of 'race' and 'cancel'.
#   https://github.com/simonmar/async/issues/59
#   https://github.com/simonmar/async/issues/81
# It has yet to appear in an LTS.
- async-2.2.1
# There are 2 asyncs -_-
- lifted-async-0.10.0.1

# Serokell-specific utilities not on stackage
- fmt-0.6
# We *must* use 6.3.6 at least, otherwise `int` is synonymous with `build` and
# will result in an infinite loop -> space leak; however we can't yet because
# CI hasn't run cabal update yet.
# - formatting-6.3.6

# Following 9 are not on stackage.
- pvss-0.2.0
- systemd-1.1.2
- base58-bytestring-0.1.0
- pipes-interleave-1.1.2
- tabl-1.0.3
- loc-0.1.3.2
- json-sop-0.2.0.3
- lens-sop-0.2.0.2
- lzma-clib-5.2.2
# The changelog for directory-1.3.1.1 indicate some potentially important
# bugfixes over directory-1.3.0.2, which is what's on lts-11.
- directory-1.3.1.1
# https://github.com/commercialhaskell/stack/issues/3151
- happy-1.19.5
# Good bug fixes in here.
- criterion-1.4.0.0

# Servant stuff not found on stackage
- servant-multipart-0.11.2
# Because of servant-quickcheck
# It defines serverSatisfiesMgr, but requires a newer hspec.
- hspec-2.5.1
- hspec-core-2.5.1
- hspec-discover-2.5.1

# Graphics stuff not found on stackage.
- Chart-diagrams-1.8.2
- graphviz-2999.19.0.0
- diagrams-core-1.4.1.1
- diagrams-lib-1.4.2
- diagrams-postscript-1.4
- diagrams-svg-1.4.1.1
- diagrams-solve-0.1.1
- SVGFonts-1.6.0.3
- dual-tree-0.2.1

# Support for wallet's Txmeta tracking
- sqlite-simple-errors-0.6.1.0

# Working around a stack issue with rebuilding dependencies
- pretty-show-1.6.16

# Needed for coin selection in the wallet
- normaldistribution-1.1.0.3

# This used to be Serokell.Aeson.Options
- aeson-options-0.0.0

# universum depends on tasty-hedgehog
# tasty-hedgehog < 0.2 depends on hedgehog < 0.6
# LTS-11.13 -- LTS-11.17 provide tasty-hedgehog-0.1.0.2
# thus to use our hedgehog-0.6+ from source,
# we need to explicilty bump tasty-hedgehog to 0.2.0.0.
- tasty-hedgehog-0.2.0.0

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

# If you find it too restrictive, you can use `scripts/build/cardano-sl.sh' script
ghc-options:
  cardano-sl:             -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-auxx:        -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-binary:      -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-binary-test: -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-block:       -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-block-test:  -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-client:      -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-core:        -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-core-test:   -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-crypto:      -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-crypto-test: -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-db:          -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-delegation:  -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-explorer:    -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-generator:   -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-infra:       -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-lrc:         -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-lrc-test:    -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-networking:  -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-node:        -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-sinbin:      -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-ssc:         -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-tools:       -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-txp:         -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-txp-test:    -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-update:      -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-util:        -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-util-test:   -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-wallet:      -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-wallet-new:  -Werror -Wcompat -fwarn-redundant-constraints
  cardano-sl-node-ipc:    -Werror -Wcompat -fwarn-redundant-constraints
