flags: {}

extra-package-dbs: []

packages:
- '.'

- location:
    git: https://github.com/serokell/universum
    commit: db3cd301545e5da000e53ca2cdf274e0386192bf
  extra-dep: true
- location:
    git: https://github.com/serokell/log-warper.git
    commit: e05d74587ff9270891a3e57f1f15d9e91c8d2c83
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 8ebc91484994fbd1b8383d42786ae40bb5c99042
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: 62b4aaf5e8dfe70a7734a555032d8461ce4a812a
  extra-dep: true
- location:
    git: https://github.com/serokell/rocksdb-haskell.git
    commit: 4dfd8d61263d78a91168e86e8005eb9b7069389e
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: 57adb970e198a9b377769ab46e776ec29f19cff6
  extra-dep: true
- location:
    git: https://github.com/serokell/tw-rework-sketch.git
    commit: 79d2efba3309ace63d03aaa4517df0c1a3cd22ba
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport-tcp.git
    commit: 586c9bf830252476522cab6274ef8ddc32615686
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- pqueue-1.3.2
- data-msgpack-0.0.8
- time-units-1.0.0
- aeson-extra-0.4.0.0
- recursion-schemes-5
- QuickCheck-2.9.2
- cryptonite-openssl-0.3
- UtilityTM-0.0.4
- serokell-util-0.1.3.0
- pvss-0.1
- base58-bytestring-0.1.0
- time-warp-1.1.1.1

resolver: lts-7.15

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything


compiler: ghc-8.0.2
