# Logging configuration
# additional output in JSON format

rotation:
    logLimit: 104857600 # 100MB
    keepFiles: 100
loggerTree:
  severity: Info+
  files:
    - node.pub
    - node
  handlers:
    - backend: FileJsonBE
      severity: Warning+
      name: Json_log
      filepath: node.json

