steps:
  - label: 'stack rebuild'
    env:
      # fixme: bucket in eu-central-1 is better for buildkite agents
      AWS_REGION: us-west-1
      S3_BUCKET: appveyor-ci-cache
      CACHE_S3_MAX_SIZE: 2500MB
    command:
      - "rm -rf /build/cardano-sl"
      - "git clone . /build/cardano-sl"
      - "cd /build/cardano-sl"
      - "nix-build scripts/ci/buildkite -o stack-rebuild"
      - "./stack-rebuild"
    agents:
      system: x86_64-linux
