{-# LANGUAGE ScopedTypeVariables #-}

-- | Command line options of pos-node.

module AnalyzerOptions
       ( Args (..)
       , argsParser
       ) where

import           Data.Monoid                ((<>))
import           Options.Applicative.Simple (Parser, auto, help, long, many, metavar,
                                             option, short, strOption)
import           Universum                  hiding ((<>))

data Args = Args
    { files             :: ![FilePath]
    , txFile            :: !FilePath
    , confirmationParam :: !Word64
    }
  deriving Show

-- TODO: introduce subcommands (can be done if new commands appear)
argsParser :: Parser Args
argsParser =
    Args <$>
    many
        (strOption
             (long "file" <> metavar "FILEPATH" <> help "JSON file to analyze")) <*>
    (strOption
         (long "tx-file" <> metavar "FILEPATH" <>
          help "JSON generated by txSender")) <*>
    (option
         auto
         (long "confirmation" <> short 'k' <>
          help "How many blocks are needed for confirmation"))
