{-# LANGUAGE ScopedTypeVariables #-}

-- | Command line options of pos-node.

module AnalyzerOptions
       ( Args (..)
       , argsParser
       ) where

import           Options.Applicative.Simple (Parser, auto, help, long, many, metavar,
                                             option, optional, short, strOption, value)
import           Universum

import           Pos.Constants              (k)

data Args = Args
    { files             :: ![FilePath]
    , txFile            :: !(Maybe FilePath)
    , confirmationParam :: !Word64
    }
  deriving Show

-- TODO: introduce subcommands (can be done if new commands appear)
argsParser :: Parser Args
argsParser = Args
    <$> many (strOption $
              long "file"
           <> metavar "FILEPATH"
           <> help "JSON file to analyze")
    <*> optional (strOption $
                  long "tx-file"
               <> metavar "FILEPATH"
               <> help "JSON generated by txSender")
    <*> option auto (long "confirmation"
                  <> short 'k'
                  <> value k
                  <> help "How many blocks are needed for confirmation")
