---
Wallets:
  -
    Accounts:
      -
        Addresses:
          - DdzFFzCqrhtCiiLVZtX8Ed8DFriGni43h8chAAoz9wCKwiQbzdLXCDGfPRY2ANavaEDDEK7DUVAHxR2oxfr9k7LwyachbkBP2FmyE47P
        AccountId: Ae2tdPwUPEZMeiDfNHZ45V7RoaSqd4oSMuG4jo7asvmNHS193EEad1tUkeT@2147483648
    WalletId: Ae2tdPwUPEZMeiDfNHZ45V7RoaSqd4oSMuG4jo7asvmNHS193EEad1tUkeT
