language: nix
sudo: true
env:
- NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/cb90e6a0361554d01b7a576af6c6fae4c28d7513.tar.gz
install:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
script:
- pushd frontend
- "./scripts/build.sh"
- nix-shell --run "yarn test"
- popd
- "./update_explorer_web_api_docs.sh"
notifications:
  email: false
  slack:
    secure: OdwiFeu7kwochdkIbVz5ZIlTa1AdItO9EFYPVHKoqGOy8s/6kkmMlb0XH4w8ZvKMSDVE2tuXBKz2cVqu0k1A3Nml/q8LF0a2zYagkpAUe4uEHBD7jTO8RCLzABw06unlIyOuNRApTUH97Dq/GftNwunkCyeY7DgzNoxm9mHB53BHaF2A/eHw6oHX3MQwGZvjuqZAT2wx7UbxEISWVWx18ZPTjCJsrDR7dwwB07IhA8oYUNk9nqE94OplLofUafBDRneDs5kEQoVmxomt6U44BIQs7acUGDvSjnmxhgEbq8rge7N5I3i0REtNQCOBeWThGkNY9H3fZfqSTeVQa7/xig8Vxu7+6G+QfOxvCp8PZP3sDACSXJvy/6gUN/sU6q8lZweuAm9BddULof6jjMhPcohRf/hu5/NmSFqYo33wZWvZaBrijBrpPOooU/16W+SbK6kKVuv8YxhnQ64wwKAlnGUcFCEcZwb4EZsMDho1VMO002yC5WmnB3+N/n3i9ncTaT1aVnXZYvkH971AOQ3uMLdICJpMPmZ5ykl8KmfL27fUwxngQzkARdioCt/WEsCLPUJP0YBfjK5GLCZdeLobAeHoE7aKp2XCIwwvoaLwo2z96HSq6OoWBZC8z60Y6ttbEwSFBe/kYU55UYCbZi4bDrtZbpiVp66QxCL9k/xv65o=
    on_success: never
    on_failure: always
