module Explorer.Types where

import Explorer.I18n.Lang (Language)
import Explorer.Routes (Route)

-- TODO (jk) Will be generated by purescript-bridge later on
data CCurrency =
      ADA
    | BTC


-- State

type State =
    { lang :: Language
    , route :: Route
    }


-- Actions

data Action
    = SetLanguage Language
    | UpdateView Route
    | ScrollTop
    | NoOp
