---
Wallets:
  -
    Accounts:
      -
        Addresses:
          - DdzFFzCqrhsxJU8JeDDS7T7rjw4chfMR3p98y89zTNE4gPeyveRccWhJknr5eoeQAqrRjAXNPH5L7q39fFpA8SoETRD8bZn6RSDm2BR4
          - DdzFFzCqrhspW7t61NskUMMgVfA4Ru8CwpnpkPumrXiMn6TanduU2tZnc2mE46bsy1sPLScxnqh2KQyYqCHhueY5SVnLsbS1STTYJ5vX
          - DdzFFzCqrhsvjq72kpopPyxQzZZDPfnYegbUeQeqX1CHec9dheFK4hTHi331RKE6MDH9FLgNjEjRS8gwyCGjLi9W7zpYmGYzAVnSLMd4
          - DdzFFzCqrht6p7oRHgCaXxKsmZwvGN8syWqcyKRpA99AS134N7WgviTSACA4wXdbKpw78DpZcpyyshmvJvt2VBPeBXFGzWzyPykufq5c
          - DdzFFzCqrhsjRHnqeMzuyUJVWhv2ebpu1vupamkvfpqizShoRxVBm8FqWff674p115fZUHLFZ9jrBA2edhPnv5KQedQDEBK99NVQdE4t
        AccountId: Ae2tdPwUPEZEK5DvxPMtnTnUfQg8coWAAbNfLEvQ4GqWTe9h8d6AEkBDMce@2147483648
    WalletId: Ae2tdPwUPEZEK5DvxPMtnTnUfQg8coWAAbNfLEvQ4GqWTe9h8d6AEkBDMce
